# Site settings
title: eAsistent Developers Blog
name: eAsistent Developers Blog
email: mclion@easistent.com
description: > # this means to ignore newlines until "baseurl:"
  The place where eAsistent developers share our world, our code and our fantasies.
author: eAsistent development team
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://easistent.github.com" # the base hostname & protocol for your site

timezone: Europe/Ljubljana
encoding: utf-8
simple_search: http://google.com/search
date_format: "%d. %m. %Y"
subscribe_rss: /atom.xml



# Build settings
#markdown: kramdown
safe: false
lsi: true
highlighter: pygments
markdown: rdiscount
permalink: /:year/:month/:day/:title/
#permalink: pretty
future: true
paginate: 30
paginate_path: "blog/page:num"

gems: []

#Social settings
twitter_username: mclion
github_username:  mclion


# Github repositories
github_user: mclion
github_repo_count: 0
github_show_profile_link: true
github_skip_forks: true

# Twitter
twitter_user: mclion
twitter_tweet_button: true

# Google +1
google_plus_one: true
google_plus_one_size: medium

# Google Plus Profile
# Hidden: No visible button, just add author information to search results
googleplus_user: 104860483897189448108
googleplus_hidden: false


# Google Analytics
google_analytics_tracking_id: UA-XXXX-Y

# Facebook Like
facebook_like: true